/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ReservarIndexImport } from './routes/reservar/index'
import { Route as HomeIndexImport } from './routes/home/index'
import { Route as AccountIndexImport } from './routes/account/index'
import { Route as RegistroIndexImport } from './routes/Registro/index'
import { Route as RecuperarPaswordIndexImport } from './routes/RecuperarPasword/index'
import { Route as LoginIndexImport } from './routes/Login/index'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const ReservarIndexRoute = ReservarIndexImport.update({
  path: '/reservar/',
  getParentRoute: () => rootRoute,
} as any)

const HomeIndexRoute = HomeIndexImport.update({
  path: '/home/',
  getParentRoute: () => rootRoute,
} as any)

const AccountIndexRoute = AccountIndexImport.update({
  path: '/account/',
  getParentRoute: () => rootRoute,
} as any)

const RegistroIndexRoute = RegistroIndexImport.update({
  path: '/Registro/',
  getParentRoute: () => rootRoute,
} as any)

const RecuperarPaswordIndexRoute = RecuperarPaswordIndexImport.update({
  path: '/RecuperarPasword/',
  getParentRoute: () => rootRoute,
} as any)

const LoginIndexRoute = LoginIndexImport.update({
  path: '/Login/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/Login/': {
      id: '/Login/'
      path: '/Login'
      fullPath: '/Login'
      preLoaderRoute: typeof LoginIndexImport
      parentRoute: typeof rootRoute
    }
    '/RecuperarPasword/': {
      id: '/RecuperarPasword/'
      path: '/RecuperarPasword'
      fullPath: '/RecuperarPasword'
      preLoaderRoute: typeof RecuperarPaswordIndexImport
      parentRoute: typeof rootRoute
    }
    '/Registro/': {
      id: '/Registro/'
      path: '/Registro'
      fullPath: '/Registro'
      preLoaderRoute: typeof RegistroIndexImport
      parentRoute: typeof rootRoute
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountIndexImport
      parentRoute: typeof rootRoute
    }
    '/home/': {
      id: '/home/'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeIndexImport
      parentRoute: typeof rootRoute
    }
    '/reservar/': {
      id: '/reservar/'
      path: '/reservar'
      fullPath: '/reservar'
      preLoaderRoute: typeof ReservarIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/Login': typeof LoginIndexRoute
  '/RecuperarPasword': typeof RecuperarPaswordIndexRoute
  '/Registro': typeof RegistroIndexRoute
  '/account': typeof AccountIndexRoute
  '/home': typeof HomeIndexRoute
  '/reservar': typeof ReservarIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/Login': typeof LoginIndexRoute
  '/RecuperarPasword': typeof RecuperarPaswordIndexRoute
  '/Registro': typeof RegistroIndexRoute
  '/account': typeof AccountIndexRoute
  '/home': typeof HomeIndexRoute
  '/reservar': typeof ReservarIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/Login/': typeof LoginIndexRoute
  '/RecuperarPasword/': typeof RecuperarPaswordIndexRoute
  '/Registro/': typeof RegistroIndexRoute
  '/account/': typeof AccountIndexRoute
  '/home/': typeof HomeIndexRoute
  '/reservar/': typeof ReservarIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/Login'
    | '/RecuperarPasword'
    | '/Registro'
    | '/account'
    | '/home'
    | '/reservar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/Login'
    | '/RecuperarPasword'
    | '/Registro'
    | '/account'
    | '/home'
    | '/reservar'
  id:
    | '__root__'
    | '/'
    | '/Login/'
    | '/RecuperarPasword/'
    | '/Registro/'
    | '/account/'
    | '/home/'
    | '/reservar/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  LoginIndexRoute: typeof LoginIndexRoute
  RecuperarPaswordIndexRoute: typeof RecuperarPaswordIndexRoute
  RegistroIndexRoute: typeof RegistroIndexRoute
  AccountIndexRoute: typeof AccountIndexRoute
  HomeIndexRoute: typeof HomeIndexRoute
  ReservarIndexRoute: typeof ReservarIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  LoginIndexRoute: LoginIndexRoute,
  RecuperarPaswordIndexRoute: RecuperarPaswordIndexRoute,
  RegistroIndexRoute: RegistroIndexRoute,
  AccountIndexRoute: AccountIndexRoute,
  HomeIndexRoute: HomeIndexRoute,
  ReservarIndexRoute: ReservarIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/Login/",
        "/RecuperarPasword/",
        "/Registro/",
        "/account/",
        "/home/",
        "/reservar/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/Login/": {
      "filePath": "Login/index.tsx"
    },
    "/RecuperarPasword/": {
      "filePath": "RecuperarPasword/index.tsx"
    },
    "/Registro/": {
      "filePath": "Registro/index.tsx"
    },
    "/account/": {
      "filePath": "account/index.tsx"
    },
    "/home/": {
      "filePath": "home/index.tsx"
    },
    "/reservar/": {
      "filePath": "reservar/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
